# coding: utf-8

"""
    User & Order API

    API do zarządzania użytkownikami i ich zamówieniami

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="User &amp; Order API",
    description="API do zarządzania użytkownikami i ich zamówieniami",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
