# coding: utf-8

"""
    User & Order API

    API do zarządzania użytkownikami i ich zamówieniami

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_order(self) -> None:
        """Test case for create_order

        Tworzy nowe zamówienie
        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Tworzy nowego użytkownika
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Usuwa użytkownika
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Pobiera szczegóły użytkownika
        """
        pass

    def test_get_user_orders(self) -> None:
        """Test case for get_user_orders

        Pobiera zamówienia użytkownika
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        Pobiera listę użytkowników
        """
        pass


if __name__ == '__main__':
    unittest.main()
